wod5e:
  hunter:
    starting_points:
      advantages: 7
      flaws: 2
      edges:
      - 
        name: Two Edges
        requirements:
        -
          type: Edge
          amount: 2
      - 
        name: One Edge and Two Perks
        requirements:
        -
          type: Edge
          amount: 1
        -
          type: Perk
          amount: 2
    
    advantages:
    -
      name: Linguistics
      multiple: true
      secondary: false
      levels:
      - 
        name: Language
        value: 1
      flaws:
      -
        name: Illiterate
        value: 2
    -
      name: Looks
      multiple: false
      secondary: false
      levels:
      -
        name: Beautiful
        value: 2
      -
        name: Stunning
        value: 4
      flaws:
      -
        name: Ugly
        value: 1
      -
        name: Repulsive
        value: 2
    -
      name: Nutritionist
      multiple: false
      secondary: false
      levels:
      -
        name: Solo Cooking
        value: 1
      -
        name: Cell Chef
        value: 2
      flaws:
    -
      name: Psychological Traits
      multiple: true
      secondary: false
      levels:
      flaws:
      -
        name: Living on the Edge
        value: 2
      -
        name: Weak-Willed
        value: 2
    -
      name: Substance Abuse
      multiple: false
      secondary: false
      levels:
      flaws:
      -
        name: Addiction
        value: 1
      -
        name: Severe Addiction
        value: 2
    -
      name: Supernatural Situations
      multiple: false
      secondary: false
      levels:
      -
        name: Unseemly Aura
        value: 2
      flaws:
      -
        name: Stigmata
        value: 1
      -
        name: Crone's Curse
        value: 2
    -
      name: Allies
      multiple: true
      secondary: true
      levels:
      -
        name: Allies
        value: 1
      -
        name: Allies
        value: 2
      -
        name: Allies
        value: 3
      -
        name: Allies
        value: 4
      -
        name: Allies
        value: 5
      flaws:
      - 
        name: Enemy
        value: 1
      - 
        name: Enemy
        value: 2
      - 
        name: Enemy
        value: 3
    -
      name: Contacts
      multiple: true
      secondary: false
      levels:
      -
        name: Contacts
        value: 1
      -
        name: Contacts
        value: 2
      -
        name: Contacts
        value: 3
      flaws:
    -
      name: Fame
      multiple: true
      secondary: false
      levels:
      -
        name: Fame
        value: 1
      -
        name: Fame
        value: 2
      -
        name: Fame
        value: 3
      -
        name: Fame
        value: 4
      -
        name: Fame
        value: 5
      flaws:
      -
        name: Infamy
        value: 2
      -
        name: Dark Secret
        value: 1
      -
        name: Infamous Partner
        value: 1
    -
      name: Influence
      multiple: true
      secondary: false
      levels:
      -
        name: Influence
        value: 1
      -
        name: Influence
        value: 2
      -
        name: Influence
        value: 3
      -
        name: Influence
        value: 4
      -
        name: Influence
        value: 5
      flaws:
      -
        name: Despised
        value: 2
      -
        name: Disliked
        value: 1
    -
      name: Mask
      multiple: true
      secondary: false
      levels:
      -
        name: Mask
        value: 1
      -
        name: Mask
        value: 2
      flaws:
      -
        name: Person of Interest
        value: 2
      -
        name: Serial Error
        value: 1
    -
      name: Zeroed
      multiple: false
      secondary: false
      levels:
      -
        name: Zeroed
        value: 1
    -
      name: Cobbler
      multiple: false
      secondary: false
      levels:
      -
        name: Cobbler
        value: 1
    -
      name: Mentor
      multiple: true
      secondary: false
      levels:
      -
        name: Mentor
        value: 1
      -
        name: Mentor
        value: 2
      -
        name: Mentor
        value: 3
      -
        name: Mentor
        value: 4
      -
        name: Mentor
        value: 5
      flaws:
      - 
        name: Adversary
        value: 1
      - 
        name: Adversary
        value: 2
      - 
        name: Adversary
        value: 3
    -
      name: Resources
      multiple: true
      secondary: false
      levels:
      -
        name: Resources
        value: 1
      -
        name: Resources
        value: 2
      -
        name: Resources
        value: 3
      -
        name: Resources
        value: 4
      -
        name: Resources
        value: 5
      flaws:
      -
        name: Destitute
        value: 1
    -
      name: Retainers
      multiple: true
      secondary: false
      levels:
      -
        name: Retainers
        value: 1
      -
        name: Retainers
        value: 2
      -
        name: Retainers
        value: 3
      -
        name: Retainers
        value: 4
      -
        name: Retainers
        value: 5
      flaws:
      -
        name: Stalkers
        value: 1
    -
      name: Status
      multiple: true
      secondary: false
      levels:
      -
        name: Status
        value: 1
      -
        name: Status
        value: 2
      -
        name: Status
        value: 3
      -
        name: Status
        value: 4
      -
        name: Status
        value: 5
      flaws:
      -
        name: Suspect
        value: 1
      -
        name: Shunned
        value: 2
    -
      name: Safe House
      multiple: true
      secondary: false
      levels:
      -
        name: Safe House
        value: 1
      -
        name: Safe House
        value: 2
      -
        name: Safe House
        value: 3
      flaws:
      -
        name: No Safe House
        value: 1
      -
        name: Compromised
        value: 2
      traits:
      -
        multiple: true
        secondary: false
        levels:
        -
          name: Hidden Armory
          value: 1
        -
          name: Panic Room
          value: 1
        -
          name: Watchmen
          value: 1
        -
          name: Laboratory
          value: 1
        -
          name: Luxury
          value: 1
        -
          name: Security System
          value: 1
        -
          name: Surgery
          value: 1
        